# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version: ["5.7", "5.8", "5.9", "5.10", "6.0"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Run tests
        run: swift test
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test
